# Generated by Django 4.1.1 on 2022-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_completion',
            name='track_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
