# Generated by Django 4.1.1 on 2022-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
